### ISSUE TITLE
 Demo-form

### ISSUE THREAD

**Issue by marina-bashlak** [HYF-Class21/agile-development-group4-loruki-rebuild#26]
- [x]  This feature developed on a branch `introduction`
- [x] Add `div`
- [x] Add `h2`
- [x]  Add `form` 
- [x] Add `div` with `input` 4times
- [x] Run all code   quality check
- [x]  Add changes
- [ ] Create a PR

**Comment by Vishal-Parasram** [comment]
@marina-bashlak Hey I want to work on this issue.
